project:
   type: website
   output-dir: docs
   
website:
  title: "Lab 6 & 8"
  navbar:
    left: 
      - href: index.qmd
      - text: Lab 6
      - href: hyperparameter-tuning.qmd
      - text: Lab 8
format: 
  html: 
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true


 




